apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: app-container
        image: gcr.io/gcp-terraform-357100/python-app:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: webapp-config-map

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: redis-container
        image: gcr.io/gcp-terraform-357100/python-app:latest
        ports:
        - containerPort: 6379
