apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
  namespace: develop-area
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        privileged: true
      containers:
      - name: jenkins
        image: rizk95/jenkins_with_docker_terra_ansible_kubectl
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50000
          name: jnlp
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker    
        - name: jenkins-pvc
          mountPath: "/var/jenkins_home"          
      volumes:
      - name: jenkins-pvc
        persistentVolumeClaim:
            claimName: jenkins-pvc
      - name: docker
        hostPath:
          path: /var/run/docker.sock