apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: backend
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30010

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service-jenkins
  namespace: develop-area
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30020

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: develop-area
spec:
  selector:
    app: jenkins
  ports:
  - port: 3000
    targetPort: 3000
